"""col data_baixado tab erros_extract

Revision ID: 39ac8c953a1e
Revises: d6b30d721539
Create Date: 2026-02-19 20:23:50.880866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ac8c953a1e'
down_revision: Union[str, Sequence[str], None] = 'd6b30d721539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erros_extract', sa.Column('data_baixado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('erros_extract', 'data_baixado')
    # ### end Alembic commands ###
