"""lote_baixado em erros_extract

Revision ID: 542e5f48e20d
Revises: ea14dcffb358
Create Date: 2026-02-20 10:29:21.755736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '542e5f48e20d'
down_revision: Union[str, Sequence[str], None] = 'ea14dcffb358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erros_extract', sa.Column('data_hora_baixado', sa.DateTime(timezone=True), nullable=True))
    op.add_column('erros_extract', sa.Column('lote_baixado', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('erros_extract', 'data_baixado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erros_extract', sa.Column('data_baixado', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('erros_extract', 'lote_baixado')
    op.drop_column('erros_extract', 'data_hora_baixado')
    # ### end Alembic commands ###
