"""col url tab erros_extract unique

Revision ID: 9938cb0f2bea
Revises: dea85d255e92
Create Date: 2026-02-19 17:12:59.369707

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9938cb0f2bea"
down_revision: Union[str, Sequence[str], None] = "dea85d255e92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "erros_extract", ["url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_erros_extract_url", "erros_extract", type_="unique")
    # ### end Alembic commands ###
