"""fix unique lote_id logs

Revision ID: afed6f9515ce
Revises: d3dcb8703f29
Create Date: 2026-02-21 21:30:20.577566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afed6f9515ce'
down_revision: Union[str, Sequence[str], None] = 'd3dcb8703f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('logs_lote_id_key'), 'logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('logs_lote_id_key'), 'logs', ['lote_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
