"""criando tabela erros_extract

Revision ID: b0bae8cf553f
Revises: bafcfc79d8ad
Create Date: 2026-02-12 21:15:09.465964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bae8cf553f'
down_revision: Union[str, Sequence[str], None] = 'bafcfc79d8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erros_extract',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erros_extract')
    # ### end Alembic commands ###
