"""tabela lote criada

Revision ID: bafcfc79d8ad
Revises: 
Create Date: 2026-02-12 18:20:50.737813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafcfc79d8ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('todos_flows_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_inicio_lote', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fim_lote', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data_inicio_extract', sa.Date(), nullable=False),
    sa.Column('data_fim_extract', sa.Date(), nullable=False),
    sa.Column('flows_ignoradas', sa.String(length=25), nullable=True),
    sa.Column('tasks_ignoradas', sa.String(length=200), nullable=True),
    sa.Column('resetar_cache', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote')
    # ### end Alembic commands ###
