"""task_run_name logs

Revision ID: d3dcb8703f29
Revises: 4834a9a2d388
Create Date: 2026-02-21 19:55:47.393476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dcb8703f29'
down_revision: Union[str, Sequence[str], None] = '4834a9a2d388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('flow_run_name', sa.String(length=256), nullable=False))
    op.add_column('logs', sa.Column('task_run_name', sa.String(length=256), nullable=True))
    op.drop_column('logs', 'flow_run')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('flow_run', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('logs', 'task_run_name')
    op.drop_column('logs', 'flow_run_name')
    # ### end Alembic commands ###
