"""coluna baixado tabela erros_extract

Revision ID: d6b30d721539
Revises: 1d547cfc200d
Create Date: 2026-02-19 20:03:04.466430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b30d721539'
down_revision: Union[str, Sequence[str], None] = '1d547cfc200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erros_extract', sa.Column('baixado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('erros_extract', 'baixado')
    # ### end Alembic commands ###
