"""add col urls_nao_baixadas tab lote

Revision ID: dea85d255e92
Revises: cfb374e35c0a
Create Date: 2026-02-19 16:53:38.972483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea85d255e92'
down_revision: Union[str, Sequence[str], None] = 'cfb374e35c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lote', sa.Column('urls_nao_baixadas', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lote', 'urls_nao_baixadas')
    # ### end Alembic commands ###
