"""correcao data_baixado sem default erros_extract

Revision ID: ea14dcffb358
Revises: 39ac8c953a1e
Create Date: 2026-02-19 21:23:46.039024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea14dcffb358'
down_revision: Union[str, Sequence[str], None] = '39ac8c953a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('erros_extract', 'mensagem',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    op.alter_column('erros_extract', 'mensagem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
